# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

forwardsBackwards <- function(prior, transmat, f_tk) {
    .Call(`_MHMMR_forwardsBackwards`, prior, transmat, f_tk)
}

